# Generated by Django 5.1.6 on 2025-03-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("xvoice", "0002_message_sentiment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
